### ISSUE TITLE
404 on site http://blockdiag.com/seqdiag/build/html/index.html

### ISSUE THREAD

**Issue by pleabargain** [blockdiag/seqdiag#40] opened 2021-06-08 06:52 UTC
http://blockdiag.com/seqdiag/build/html/index.html

404 Not Found
Code: NoSuchKey
Message: The specified key does not exist.
Key: seqdiag/build/html/index.html
RequestId: FV802ZDYX8V88ZRF
HostId: 07j8Z7KORtT42P/XMX5VuQ7Ug+ktOJCvb9YS8eNEIgj9rZ4Vj9XKUaUAlGQjMr8hwWdRda0T4U4=

**Comment by tk0miya** [comment] 2021-06-20 11:13
Where the URL came from? The top page of seqdiag is http://blockdiag.com/en/seqdiag/index.html. I think this is not a bug. Closing.

**Closed by tk0miya** 2021-06-20 11:13 UTC
